name: elite_prestations
description: Application mobile Élite Prestations - Agence événementielle au Gabon
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Navigation
  go_router: ^18.0.2
  flutter_riverpod: ^3.4.3
  cupertino_icons: ^2.0.0
  google_fonts: ^8.0.0
  cached_network_image: ^4.0.4
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1
  state_notifier: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
